language: ruby
rvm:
  - 2.3.0
deploy:
  api_key:
    secure: cuJqeLoyPznFC9kWYcMBaQ+i1CQEEJqzW3gbkqZSd4LGabiWjlTlbc9Y3D4UY/uGpVK0nOu7StkrMqEf8cxapecW9Tsz/SzKyHxmkapJdNJEjqQpG8uebrcQrAD0dePPAX93ykNdNquYfVpynq6rrYwO/QKkZqxESYuj+z9CUWaj1Pg1amTTqWhvAS6rndWLqIuojfyR5cjJF/aA+YmPK4SXol7yfs30+G7mUOKJCmNGgMedaAQJKcuAWscDFnsdPEG21uNZQJ1E3VzBtD0s6VCelQkedHt706ZQD+OBjU4Hz6r0/vRwbPLzJXq5W4k8CmmwAL5c8Tz3051i+CwJhMAVs6jEb1nrOmuqO6YsEX/Mf4dJ+UfaNzcsECAHPlMUYiw3fcUu0FJ0ZbjhzZoH+jGSLj40ifGDJEplQ/WJnsP+kfkphYu1yg1jGsKXss3IC0N9QqO7xWdbVeTxwOQo3ohgOCZybTmwFc1kyXxWosXPzv26N+guFYp+wiJB3/MnLvIdseANIcNMO9jjuHEMXHOcTrfjtubjCgHwfpwoXb6cTz8Rdccv5niSCxVJlzmM0NJ71hRZDVDWDSjIhl+v5QjMbxMUcE3GDXqK0JbDaf4BHz57aR860CNW0BjcRClFjEg9E0NMugF1hZaNTvIlrFOkt0bpnVQRTHuZCPCwkA8=
