before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - bundle exec rackup &
  - sleep 3
  - psql -c 'create database blog_test;' -U postgres
language: ruby
rvm:
  - 2.3.0
deploy:
  provider: heroku
  api_key:
    secure: hcUMRX6vfnJnnFSMtgyNAHwl8daGfo3/5W128rrUGiVMPdZnKSDQGb74RV0YSx/t6q8+Zd0PxJ9WGArepCev+zWLu4rxKTdZu5+0GgkkRvjnZHm1O1+Z95MdTMW63LKfE0zcvhsqYCMJWMBiSjx1p+m1xWOZfrKRWDGhMcogq914QrYSxq1+ipS5yA+eNfJtqU3UXNWAEFfOU4jCUz4BLqOCkj8JwJsi0Q22kooVwOi5doZoqPMCTaPbfx0RiKr5uI3skR2dfYONnUuO5LebGo8Abr3LxwhMnT2Yf1+2AjAHKInOXZ9OYqeZ3lNUiUrZtyxOATmSLSmVT0rZEXWHU+EOGgz19yE6gRIzbiuHisYrsGiAtJiwBU17fyKjm0BS5M53wXrFb2Gmglj7jUW152ofsm2aG+qUOLQfIgrOABcYnBDjKG+kf93ecPWvRaeK1UPuuMaE2mNEZf+bFQRd/k+ojAuiqlMEEn8c1H7ZjvD1U0OG7dInIa8voatcnPJkLvS6NkPJEYczFL3hGxNnuQlMhJ9mvewASqkLhKf/EX7FJOC4sI8/m8pFe/M7/rFl95Qp5UQDyOdAE85hntkGQyNCq4tDlEtdcH46B7Y3u2QtpPnj68qbEOcqTSvez0DgkPtZzrRXHlsFPgOKBn+0UwYT7xc10krob/SnUw45ysM=
  app: rails--blog
  on:
    repo: krlsdu/rails-blog
addons:
  code_climate:
    repo_token:
      secure: bpa+TdGGqhJSIidZy15saWAV75ALH6ZKSaLir8L4ZogXSqgm6T5zASnd/z8RWB2XBWEW//ITCiR2P3jVzfNcWRaqpCCsEIFSQCP85f5pE0+Ih4NHtc4t7EFAiDFdCnDTia9sBYBpGKxGoQRG67VgJUpH2CaksaBkBjO5LnrsrTuaQ3NXAz78jiedN+Jj750t9y0so4/nC/45lyA7Ti86FTiycad41w5Lt9YnDYga1HhGhjXMcrMCn9qaotL7MgtC5EWfOJTpIfsuBzDCyMjbgoVhLKn99HxvkLj0a4s5mNnJeztJrFOCvbbkoyK325uFLFATMhZiylXULtoFTmF1v/vtDhXSQcsVgdZEfp33Pq8RsnUG0ApvdbEK4XH66Zwl45SDa626eOUoJgqCrDenFD/vhJ7P5gC9ptPaow8GVSTNi/B3IBGuZyBXmosGiKrIpXtL8Cor8Yaw3+dv1njbV2l22d4+Ed7u4UAPVV1t4SdIzC4yFGeywUHaJHble9PcDRctnj5OuTmaLfjbT4+DW3ksifrNzcBRWRPROplOVrXYqccYM+SnkMsGJdMZ+rDMtIKq2pUE/8BgrWwzmXFoEBERsaBw5AzmdgM1dFbzAMmc8hBLp73vFP9gJ/SR4ctjCTCdJ1Ca8vwIDfRYg36ytyzO6MXjxnYxLncv175n74k=

