# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd1bc251db599b591470306e68b72168bc2635820976a860fc1a248ec83d0de00e948e9f977021d27cb75b5eef503768fad7fd7dab4b0f2c8d92fb2b91b10b5f

test:
  secret_key_base: 859a253a3a3dca9180ae645b821f4c866e925eca99ae2d94da98f23dacd769b34732d2b9658fd5e58371e1cc9597a25578040e7542efe9717de240496cfa25d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
